# Generated by Django 3.2.5 on 2021-08-16 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=400)),
                ('image', models.CharField(max_length=200)),
                ('play_time', models.DecimalField(decimal_places=1, max_digits=4)),
                ('type_of_game', models.CharField(choices=[('AC', 'Action'), ('AR', 'Arcade'), ('PL', 'Platform'), ('SH', 'Shooter'), ('AD', 'Adventure'), ('SP', 'Sport'), ('CA', 'Cars'), ('ST', 'Strategy'), ('SI', 'Simulation')], default='AC', max_length=2)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videogames', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_network_link', models.CharField(blank=True, max_length=100)),
                ('steam_user', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('image', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to=settings.AUTH_USER_MODEL)),
                ('video_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='lfg_api.videogame')),
            ],
        ),
    ]
